### ISSUE TITLE
Undefined function _qrCodeContainerAdd

### ISSUE THREAD

**Issue by wojinwomacka** [LostInBrittany/granite-qrcode-generator#3]
Hello,
I have no idea why and how. But on line `172` in `granite-qrcode-generator.html` you are calling `this._qrCodeContainerAdd(img);` . Can you explain why? There is no such a function and it is throwing error  `this._qrCodeContainerAdd is not a function`. 

Rewriting line `172` to `this._appendQRCode(img);` resolve this issue. 

Another great feature would be to add some custom styling to created IMG so something like:

```
img {
  @apply --img-element;
}
```

**Comment by LostInBrittany** [comment]
It's a sad remain of a first version of the component... I was almost sure I had removed it, doing it now...
