### ISSUE TITLE
QR stoped working

### ISSUE THREAD

**Issue by AbdChahid** [LostInBrittany/granite-qrcode-generator#7]
Hello,
I was using granite-qrcode-generator for a while  now, and it just stoped working I don't know why ... any Ideas ?

**Comment by LostInBrittany** [comment]
I think I would need some more information of how, which versions, with
browsers, if the demo still works for you...

**Comment by AbdChahid** [comment]
this is the typical line that Im using,
<granite-qrcode-generator data="Hello World" mode="alphanumeric" margin="2" auto></granite-qrcode-generator>
I tried it on chrome, mozilla and Microsoft Edge, it was working fine and one day I got nothing, I don't understand why.

**Comment by AbdChahid** [comment]
This is the typical line that Im using :

`<granite-qrcode-generator data="kokolokih" mode="alphanumeric" margin="2" auto></granite-qrcode-generator>`

I tried it, on mozilla, chrome and microsoft Edge. everything was working fine, until one day. I don't understand why

**Comment by LostInBrittany** [comment]
Just migrated everything to new versions of library, if the problem still there, please re-open
