### ISSUE TITLE
Any workaround for qr.js not accepting '_' underscore in 'data', as is often in a URL?

### ISSUE THREAD

**Issue by davidmaxwaterman** [LostInBrittany/granite-qrcode-generator#8]
It seems like qr.js doesn't realise `_` is fine in a URL. Unfortunately, ALPHANUMERIC_REGEXP doesn't include an `_`, so it throws an exception :/:
```
^[A-Za-z0-9 $%*+\-./:]*$
```

**Comment by LostInBrittany** [comment]
I have forked qr.js, to make it ESM compatible. I am going to look at that and try to fix

**Comment by davidmaxwaterman** [comment]
please let me know the fixed version :)

**Comment by LostInBrittany** [comment]
Hmm, it seems `_` is not an accepted character for QR code normes...
I know it's used in URL (even if considered a bad practice) but I am not sure if there is
a workaround, because QR code decoders wouldn't decode it anyways,
